# Generated by Django 4.2.4 on 2023-08-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_remove_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('Station Owner', 'stowner'), ('Vehicle Owner', 'vhowner'), (3, 'admin')], null=True),
        ),
    ]
