# Generated by Django 4.2.4 on 2023-08-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('Station Owner', 'stowner'), ('Vehicle Owner', 'vhowner'), ('Admin', 'admin')], max_length=50, null=True),
        ),
    ]
