# Generated by Django 4.2.2 on 2023-09-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('stowner', 'stowner'), ('vhowner', 'vhowner'), ('admin', 'admin')], null=True),
        ),
    ]
