# Generated by Django 4.2.2 on 2023-09-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('stowner', 'stowner'), ('vhowner', 'vhowner'), ('admin', 'admin')], max_length=100, null=True),
        ),
    ]
