# Generated by Django 4.2.4 on 2023-09-09 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('stowner', 'stowner'), ('vhowner', 'vhowner'), ('admin', 'admin')], default='vhowner', max_length=100, null=True),
        ),
    ]
