# Generated by Django 4.2.4 on 2024-02-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_otpmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('stowner', 'stowner'), ('vhowner', 'vhowner'), ('admin', 'admin'), ('worker', 'worker')], default='vhowner', max_length=100, null=True),
        ),
    ]
