# Generated by Django 4.2.4 on 2024-02-20 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='add_service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='', upload_to='pic')),
                ('ser_name', models.CharField(default='', max_length=30)),
                ('description', models.CharField(default='', max_length=250)),
                ('price', models.FloatField(null=True)),
                ('status', models.BooleanField(default=False)),
                ('delete_status', models.BooleanField(default=False)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_by_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='service_station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stname', models.CharField(default='', max_length=30)),
                ('ownername', models.CharField(default='', max_length=25)),
                ('place', models.CharField(default='', max_length=30)),
                ('photo', models.ImageField(default='', upload_to='pic')),
                ('latitude', models.CharField(max_length=12, null=True)),
                ('longitude', models.CharField(max_length=12, null=True)),
                ('maxslot', models.IntegerField(default='4')),
                ('description', models.CharField(default='', max_length=250)),
                ('contact', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(null=True)),
                ('hidden', models.BooleanField(default=False)),
                ('available', models.IntegerField(null=True)),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),

        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.IntegerField()),
                ('is_favorite', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='add_service',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='make_service.service_station'),
        ),
        migrations.CreateModel(
            name='add_package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(default='', max_length=30)),
                ('duration', models.CharField(default='', max_length=30)),
                ('package_desc', models.CharField(default='', max_length=250)),
                ('orginal_price', models.FloatField(null=True)),
                ('discount_price', models.FloatField(null=True)),
                ('package_image', models.ImageField(default='', upload_to='pic')),
                ('package_status', models.BooleanField(default=False)),
                ('package_del_status', models.BooleanField(default=False)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_by_name', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='make_service.add_service')),
            ],
        ),
    ]
