# Generated by Django 4.2.4 on 2024-02-20 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('make_service', '0002_service_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_booking',
            name='service',
        ),
        migrations.RemoveField(
            model_name='service_booking',
            name='station',
        ),
        migrations.AddField(
            model_name='service_booking',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='make_service.add_package'),
        ),
    ]
