# Generated by Django 4.2.4 on 2024-02-21 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('make_service', '0006_alter_service_booking_slotnumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_service',
            old_name='service',
            new_name='station',
        ),
    ]
