# Generated by Django 4.2.4 on 2024-02-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_service', '0007_rename_service_add_service_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_booking',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service_booking',
            name='payment_done',
            field=models.BooleanField(default=False),
        ),
    ]
