# Generated by Django 4.2.4 on 2024-02-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_service', '0008_service_booking_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_booking',
            name='desc',
            field=models.CharField(default='', max_length=250),
        ),
    ]
