# Generated by Django 4.2.4 on 2024-02-21 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('make_service', '0009_service_booking_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_service',
            old_name='station',
            new_name='service',
        ),
    ]
