# Generated by Django 4.2.4 on 2024-02-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_service', '0011_additionalservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalservice',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
