# Generated by Django 4.2.4 on 2024-02-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_service', '0012_alter_additionalservice_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalservice',
            name='cost',
            field=models.FloatField(null=True),
        ),
    ]
