# Generated by Django 4.2.4 on 2024-02-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_service', '0013_alter_additionalservice_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalservice',
            name='total_cost',
            field=models.FloatField(null=True),
        ),
    ]
