# Generated by Django 4.2.4 on 2024-02-22 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_service', '0014_additionalservice_total_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalservice',
            name='total_cost',
            field=models.FloatField(default=0.0),
        ),
    ]
