# Generated by Django 4.2.4 on 2024-02-22 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('make_service', '0016_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='station_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='make_service.service_station'),
        ),
    ]
