# Generated by Django 4.2.4 on 2024-02-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_service', '0017_alter_favorite_station_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='comment_date',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='email',
        ),
        migrations.AddField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='likes',
        ),
        migrations.AddField(
            model_name='feedback',
            name='likes',
            field=models.IntegerField(null=True),
        ),
    ]
