# Generated by Django 4.2.4 on 2024-02-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_service', '0019_feedback_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
