# Generated by Django 4.2.4 on 2024-03-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_service', '0021_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_booking',
            name='del_status',
            field=models.BooleanField(default=False),
        ),
    ]
