# Generated by Django 4.2.4 on 2024-03-13 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_service', '0022_service_booking_del_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='likes',
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
