# Generated by Django 4.2.4 on 2023-10-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_holiday', models.CharField(max_length=10)),
                ('temperature', models.FloatField()),
                ('hour', models.IntegerField()),
                ('month_day', models.IntegerField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('weekday', models.IntegerField()),
                ('location', models.CharField(max_length=10)),
                ('prediction', models.CharField(max_length=10)),
            ],
        ),
    ]
