# Generated by Django 4.2.4 on 2024-01-23 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='booknow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownername', models.CharField(default='', max_length=25)),
                ('stname', models.CharField(default='', max_length=30)),
                ('place', models.CharField(default='', max_length=30)),
                ('photo', models.ImageField(default='', upload_to='pic')),
                ('slotnumber', models.IntegerField(default='')),
                ('price', models.CharField(max_length=12)),
                ('date', models.DateField()),
                ('time', models.TimeField(null=True)),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('status', models.BooleanField(default=False)),
                ('del_status', models.BooleanField(default=False)),
                ('email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings_by_email', to=settings.AUTH_USER_MODEL)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings_by_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_type', models.CharField(blank=True, max_length=40, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('validity', models.CharField(blank=True, choices=[('1 MONTH', '1 MONTH'), ('2 MONTH', '2 MONTH'), ('3 MONTH', '3 MONTH'), ('4 MONTH', '4 MONTH'), ('5 MONTH', '5 MONTH'), ('6 MONTH', '6 MONTH'), ('7 MONTH', '7 MONTH'), ('8 MONTH', '8 MONTH'), ('9 MONTH', '9 MONTH'), ('10 MONTH', '10 MONTH'), ('11 MONTH', '11 MONTH'), ('12 MONTH', '12 MONTH')], max_length=40, null=True)),
                ('features', models.CharField(default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stname', models.CharField(default='', max_length=30)),
                ('ownername', models.CharField(default='', max_length=25)),
                ('place', models.CharField(default='', max_length=30)),
                ('photo', models.ImageField(default='', upload_to='pic')),
                ('latitude', models.CharField(max_length=12, null=True)),
                ('longitude', models.CharField(max_length=12, null=True)),
                ('maxslot', models.IntegerField(default='4')),
                ('description', models.CharField(default='', max_length=250)),
                ('price', models.CharField(max_length=12)),
                ('contact', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(null=True)),
                ('hidden', models.BooleanField(default=False)),
                ('available', models.IntegerField(null=True)),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='station_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        
        migrations.CreateModel(
            name='On_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(default='123', max_length=30, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_id', models.CharField(default='123', max_length=30, null=True)),
                ('status', models.BooleanField(default=False)),
                ('booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.booknow')),
                ('subscribe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.subscription')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='booknow',
            name='station_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_id', to='bookings.station'),
        ),
    ]
