# Generated by Django 4.2.2 on 2023-09-17 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stname', models.CharField(default='', max_length=30)),
                ('ownername', models.CharField(default='', max_length=25)),
                ('place', models.CharField(default='', max_length=30)),
                ('photo', models.ImageField(default='', upload_to='pic')),
                ('latitude', models.CharField(max_length=12)),
                ('longitude', models.CharField(max_length=12)),
                ('maxslot', models.IntegerField(default='4')),
                ('description', models.CharField(default='', max_length=250)),
                ('price', models.CharField(max_length=12)),
                ('contact', models.IntegerField(blank=True, null=True)),
                ('hidden', models.BooleanField(default=False)),
                ('available', models.IntegerField(null=True)),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='station_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='booknow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownername', models.CharField(default='', max_length=25)),
                ('stname', models.CharField(default='', max_length=30)),
                ('place', models.CharField(default='', max_length=30)),
                ('photo', models.ImageField(default='', upload_to='pic')),
                ('slotnumber', models.IntegerField(default='')),
                ('price', models.CharField(max_length=12)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings_by_email', to=settings.AUTH_USER_MODEL)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings_by_name', to=settings.AUTH_USER_MODEL)),
                ('station_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_id', to='bookings.station')),
            ],
        ),
        migrations.CreateModel(
            name='BookingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownername', models.CharField(default='', max_length=25)),
                ('stname', models.CharField(default='', max_length=30)),
                ('place', models.CharField(default='', max_length=30)),
                ('photo', models.ImageField(default='', upload_to='pic')),
                ('slotnumber', models.IntegerField(default='')),
                ('price', models.CharField(max_length=12)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.BooleanField(default=False)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_by_email', to=settings.AUTH_USER_MODEL)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_by_name', to=settings.AUTH_USER_MODEL)),
                ('station_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historystation_id', to='bookings.station')),
            ],
        ),
    ]
